
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dio_project?createDatabaseIfNotExist=true
    username: postgres
    password: Alfred@008
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

